### ISSUE TITLE
not working with TB 60.0 (64-bit) 

### ISSUE THREAD

**Issue by hdatma** [BobSoft3000/tb-sensitivity-header#3]

**Comment by BobSoft3000** [comment]
Hi.
I just installed the semi/unofficial Windows 64 bit build of Thunderbird 60.0 from ftp.mozilla.org, sent myself an email with sensitivity set to 'Private', and the email came through with the header just fine.
Can you provide any further details regarding which specific part of the addon is not working for you so I can investigate?

**Comment by BobSoft3000** [comment]
nmn

**Comment by hdatma** [comment]
Please check the following variable in your TB configuration: 
> extensions.strictCompatibility

It should be set to "true". I think yours is set to "false".

**Comment by BobSoft3000** [comment]
Mine is set to 'true' which is the default setting.

What specific error are you getting?  Or is the addon not showing up properly in your list of installed addons?

**Comment by hdatma** [comment]
![sh2](https://user-images.githubusercontent.com/1321219/44926547-50825b80-ad41-11e8-9527-6c5a85d526ba.png)

**Comment by BobSoft3000** [comment]
Thanks for that.  When I look at the addon on my system, it shows a custom icon, thumbnail screen shot, more descriptive text, and gives me options regarding Automatic Updates (Default/On/Off), which leads me to think you didn't install the addon from the official mozilla/thunderbird addons site?  If that's the case, please can you try uninstalling it and installing it from there instead?  If you did install it from there, please let me know if your Thunderbird is set to allow automatic updates.

https://addons.thunderbird.net/en-US/thunderbird/addon/sensitivity-header/

The code published to the Mozilla/TB site is _identical_ to what's here, but the site lets developers specify which versions of Thunderbird their addon works with.  Hence, I can login to the site and increase the maximum TB version whenever necessary, and that will be propagated to all the users automatically without me changing any code or uploading new versions.  My assumption is that because the version published _here_ specifies a maximum TB version of 43.0, which was the latest TB version that worked when I published it, your Thunderbird isn't using the automatic update process to check that it will work with more recent versions.
